# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/gatsby"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/gatsby-source-filesystem"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/gatsby-source-contentful"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/gatsby-source-wordpress"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/gatsby-plugin-sharp"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/gatsby-transformer-sharp"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/gatsby-plugin-image"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/starters/blog/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/starters/default/"
    schedule:
      interval: "daily"
